config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctorprofiles
  resources :patients
  devise_for :users
  


root 'homepage#index'



get '/signedinuserprofile' => 'doctorprofiles#signedinuserprofile'
get '/doctorprofiles/:id', to: 'doctorprofiles#show', as: 'doctorprofile_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer>


  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="google.com"> HealthCareClinic.com</a>
  </div>

  
  
  


</footer>

app/views/partials/_login_page.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-secondary btn-m" %><br />
<% end %>
<br/>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-secondary btn-m" %><br />
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">HealthCare Clinic</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to("Home", root_path , :class => "nav-link")%>
          </li>
          <li class="nav-item active">
              <%= link_to('Doctorprofile', doctorprofiles_path, :class => "nav-link") %>
          </li>
          <li class="nav-item active">
            <%= link_to("Patients", patients_path , :class => "nav-link")%>
          </li>
          <li class="nav-item active">
            <%= link_to("Appointments", appointments_path, :class => "nav-link") %>
          </li>
          
          
        </ul>
        <h7 id = "nav-bar-current-user-email" style="color: white; margin-right: 20px;"> Welcome! <%#= current_user.email %> </h7>

        <form class="form-inline mt-2 mt-md-0">

          <br>
          <br>
          <%= link_to('Log out', destroy_user_session_path, :method => :delete, :class => "btn btn-outline-info") %>
        </form>
      </div>
</nav>