config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctorprofiles
  resources :patients
  devise_for :users
  


root 'homepage#index'



get '/signedinuserprofile' => 'doctorprofiles#signedinuserprofile'
get '/doctorprofiles/:id', to: 'doctorprofiles#show', as: 'doctorprofile_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/doctorprofile.rb
class Doctorprofile < ApplicationRecord
  belongs_to :user
  has_many :appointments
validates :name, presence: true
validates :address, length: { maximum: 200 }
validates :contactNumber, numericality: { only_integer: true}

def self.search(search)
 where("name LIKE ?", "%#{search}%") 
end
end

app/controllers/doctorprofiles_controller.rb
class DoctorprofilesController < ApplicationController
  before_action :set_doctorprofile, only: [:show, :edit, :update, :destroy]
#only admin can edit or delete doctor
  #before_filter :authenticate_user! before_filter :ensure_admin, :only
#=> [:edit, :destroy]
#Got error for above(syntax error unexpected '\n') so using below
#before_action :ensure_current_user

def ensure_admin
unless current_user && current_user.admin?
render :text => "Access Error Message", :status => :unauthorized
 end
end

def signedinuserprofile doctorprofile =
Doctorprofile.find_by_user_id(current_user.id) 

if doctorprofile.nil?
redirect_to "/doctorprofiles/new"
else
#@doctorprofile = Doctorprofile.find_by_user_id(current_user.id) redirect_to
#"/doctorprofiles/#{@doctorprofile.id}" 
redirect_to root_path
end
end



  # GET /doctorprofiles
  # GET /doctorprofiles.json
  def index
    @doctorprofiles = Doctorprofile.all
if params[:search]
    @doctorprofiles = Doctorprofile.search(params[:search]).order("created_at DESC")
  else
    @doctorprofiles = Doctorprofile.all.order("created_at DESC")
  end
  end

  # GET /doctorprofiles/1
  # GET /doctorprofiles/1.json
  def show
  end

  # GET /doctorprofiles/new
  def new
      @doctorprofile = Doctorprofile.new
      puts current_user.id

      respond_to do |format|
          format.html #new.html.erb
          format.json {
              render json: @doctorprofile
           }
       end
   end

  # GET /doctorprofiles/1/edit
  def edit
  end

  # POST /doctorprofiles
  # POST /doctorprofiles.json
  def create
    @doctorprofile = Doctorprofile.new(doctorprofile_params)

    respond_to do |format|
      if @doctorprofile.save
        format.html { redirect_to @doctorprofile, notice: 'Doctorprofile was successfully created.' }
        format.json { render :show, status: :created, location: @doctorprofile }
      else
        format.html { render :new }
        format.json { render json: @doctorprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctorprofiles/1
  # PATCH/PUT /doctorprofiles/1.json
  def update
    respond_to do |format|
      if @doctorprofile.update(doctorprofile_params)
        format.html { redirect_to @doctorprofile, notice: 'Doctorprofile was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctorprofile }
      else
        format.html { render :edit }
        format.json { render json: @doctorprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctorprofiles/1
  # DELETE /doctorprofiles/1.json
  def destroy
    @doctorprofile.destroy
    respond_to do |format|
      format.html { redirect_to doctorprofiles_url, notice: 'Doctorprofile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctorprofile
      @doctorprofile = Doctorprofile.find(params[:id])
    end

    
    def doctorprofile_params
      params.require(:doctorprofile).permit(:name, :contactNumber, :address, :user_id)
    end
end

app/helpers/doctorprofiles_helper.rb
module DoctorprofilesHelper
end

app/views/doctorprofiles/_form.html.erb
<%= simple_form_for(@doctorprofile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :contactNumber %>
    <%= f.input :address %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
      <div style="display: flex; float: left;">
          <%= link_to 'Back', @doctorprofile, class: "btn btn-dark btn-m" %>
      </div>
      <div style="display: flex; float: right;">
          <%= f.button :submit , class: "btn btn-success btn-m" %>
      </div>
  </div>

<% end %>

app/views/doctorprofiles/edit.html.erb
<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Edit Doctor profile
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', profile: @doctorprofile %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">
    </div>
</div>
<br><br>

app/views/doctorprofiles/index.html.erb
<%= render 'partials/navbar' %>

<div class="jumbotron jumbotron-fluid">
<div class="container">

<h1 style="text-align: center;">Doctors</h1>

<div id="top-container">
    <!-- adding doctor to database -->
    <div id="doctorprofile_add" style="float: right"><%= link_to 'New Doctor', new_doctorprofile_path, class: "btn btn-success btn-m" %></div>
    <!-- Search bar for searching doctors -->
    <div id="search_bar" style="float: left">

        <!-- Search bar -->
<p>
<%= form_tag(doctorprofiles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Doctors by name" %>
    <%= submit_tag "Search By Name", :name => nil %>
    
<% end %>
</p>
</div>
<br>
<br>

<table class="table">
  <thead class="thead-dark">
    <tr>
       <th scope="col">Name</th>
      <th scope="col">Contact Number</th>
      <th scope="col">Address</th>
	<th scope="col">User</th>
	<th scope="col">ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctorprofiles.each do |doctorprofile| %>
      <tr>
        <td><%= doctorprofile.name %></td>
        <td><%= doctorprofile.contactNumber %></td>
        <td><%= doctorprofile.address %></td>
        <td><%= doctorprofile.user %></td>
        <td><%= doctorprofile.id %></td>
        <td><%= link_to 'Show', doctorprofile %></td>
        <td><%= link_to 'Edit', edit_doctorprofile_path(doctorprofile) %></td>
        <td><%= link_to 'Delete', doctorprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

<%= render 'partials/footer' %>

app/views/doctorprofiles/new.html.erb
<hr class="colorgraph">
<div class="jumbotron" id="signup_jumbo">

<h2 style= "text-align: center">Create Doctor Profile <b></h2><br>

<%= render 'form', profile: @doctorprofile %>

</div>
<hr class="colorgraph">

app/views/doctorprofiles/show.html.erb
  
<%= render 'partials/navbar' %>

<br/><br/>
<div class="container ">
    <div class="jumbotron ">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <img src="https://www.svgimages.com/svg-image/s5/man-passportsize-silhouette-icon-256x256.png" alt="stack photo" class="img">
            </div>
            
                
                <hr>

                <ul class="container details">
                    <!--  email address -->
                    <li><p ><span class="fas fa-envelope " style="width:50px;" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></span><%= current_user.email %></p></li>
                    <!-- Name -->
                    <li><p><span class="fas fa-map-marker-alt" style="width:50px;"></span>Name : <%= @doctorprofile.name %></p></li>
                    <!-- Address -->
                    <li><p><span class="fas fa-map-marker-alt" style="width:50px;"></span>Address : <%= @doctorprofile.address %></p></li>
                    <!-- Contact Number -->
                    <li><p><span class="far fa-id-card" style="width:50px;" title="Tools" ></span>Contact Number : <%= @doctorprofile.contactNumber %></p></li>
                    
                  
                </ul>
            </div>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
    
    <%= link_to 'Edit Doctor Profile', edit_doctorprofile_path(@doctorprofile), class: "btn btn-secondary btn-m" %> |
    <%= link_to 'Back', doctorprofiles_path, class: "btn btn-secondary btn-m" %>   |
        
    </div>
</div>

<%= render 'partials/footer' %>