config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctorprofiles
  resources :patients
  devise_for :users
  


root 'homepage#index'



get '/signedinuserprofile' => 'doctorprofiles#signedinuserprofile'
get '/doctorprofiles/:id', to: 'doctorprofiles#show', as: 'doctorprofile_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ApplicationRecord
has_many :appointments
validates :name, presence: true
validates :address, length: { maximum: 200 }
validates :contactNumber, numericality: { only_integer: true}

def self.search(search)
 where("name LIKE ?", "%#{search}%") 
end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!



  # GET /patients
  # GET /patients.json
  def index
	@patients = Patient.all
  end

def index
@patients = Patient.all
  if params[:search]
    @patients = Patient.search(params[:search]).order("created_at DESC")
  else
    @patients = Patient.all.order("created_at DESC")
  end

end




  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :contactNumber, :address, :gender, :dob, :ppsNumber)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for(@patient) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.input :name %>
    <%= f.input :contactNumber, :label => "Contact Number" %>
    <%= f.input :address %>
    <%= f.input :gender , :collection => %w[Male Female]%>
    <%= f.input :dob, :label => "Date of Birth(dd-mm-yyyy)" %>
    <%= f.input :ppsNumber, :label => "PPS" %>
    
  </div>

  <div class="form-actions">
      <div style="display: flex; float: left;">
          <%= link_to 'Back', @patient, class: "btn btn-dark btn-m" %>
      </div>
      <div style="display: flex; float: right;">
          <%= f.button :submit , class: "btn btn-success btn-m" %>
      </div>
  </div>

<% end %>

app/views/patients/edit.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Edit Patient
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', patient: @patient %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">

    </div>

</div>
<br><br>

<%= render 'partials/footer' %>

app/views/patients/index.html.erb
<%= render 'partials/navbar' %>

<div class="jumbotron jumbotron-fluid">
<div class="container">

<h1 style="text-align: center;">Patients</h1>

<div id="top-container">
    <!-- adding patient to database -->
    <div id="patient_add" style="float: right"><%= link_to 'New Patient', new_patient_path, class: "btn btn-success btn-m" %></div>
    <!-- Search bar for searching patients -->
    <div id="search_bar" style="float: left">

        <!-- Search bar -->
<p>
<%= form_tag(patients_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search patients by name" %>
    <%= submit_tag "Search By Name", :name => nil %>
    
<% end %>
</p>
</div>
<br>
<br>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Contact Number</th>
      <th scope="col">Address</th>
      <th scope="col">Gender</th>
      <th scope="col">dob</th>
      <th scope="col"><%= UserDecorator.new(@patient).pps_to_uppercase%></th>
      <th scope="col">ID</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
      
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.contactNumber %></td>
        <td><%= patient.address %></td>
        <td><%= patient.gender %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.ppsNumber %></td>
        <td><%= patient.id %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
</div>

<%= render 'partials/footer' %>

app/views/patients/new.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Add Patient
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', patient: @patient %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">

    </div>

</div>
<br><br>
<%= render 'partials/footer' %>

app/views/patients/show.html.erb
<%= render 'partials/navbar' %>

<br/><br/>
<div class="container ">
    <div class="jumbotron ">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
            <img src="https://www.svgimages.com/svg-image/s5/man-passportsize-silhouette-icon-256x256.png" alt="stack photo" class="img">

            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container">
                    <h2 style="text-align:center;">
                        <%= @patient.name %>
                    </h2>
                </div>
                <hr class="colorgraph">

                <ul class="container details">
                    
                    <li><p>Contact Number : <%= @patient.contactNumber %></p></li>                    
                    <li><p>Address : <%= @patient.address %></p></li>
                    <li><p>Gender : <%= @patient.gender %></p></li>
                    <li><p>Date of Birth :  <%= @patient.dob %></p></li>
                    <li><p>PPS Number :  <%= @patient.ppsNumber %></p></li>
                    
                </ul>
            </div>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
        <%= link_to 'Back', patients_path , class: "btn btn-dark btn-m"%> |
        <%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-warning btn-m" %>
    </div>
</div>
<%= render 'partials/footer' %>