config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :doctorprofiles
  resources :patients
  devise_for :users
  


root 'homepage#index'



get '/signedinuserprofile' => 'doctorprofiles#signedinuserprofile'
get '/doctorprofiles/:id', to: 'doctorprofiles#show', as: 'doctorprofile_user'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment < ApplicationRecord
# Validate to ensure our current user does not have a conflicting appointment
validates :date, uniqueness: { scope: :user }

  belongs_to :user
  belongs_to :doctorprofile
  belongs_to :patient


  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
#show appointments of current user
     #@appointments = current_user.appointments.all
  end




  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)


# Need to set doctorprofile ID to the foreign key
   # @appointment.user = current_user


    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def appointment_params
      params.require(:appointment).permit(:user_id, :doctorprofile_id, :patient_id, :notes, :date)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= simple_form_for(@appointment) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <!-- Show only patients to the current logged in users -->
  <div class="form-inputs">
  
    <%= f.input :doctorprofile, :label => "Doctor" %>
    <%= f.input :patient %>
    <%= f.input :notes %>
    <%= f.input :date %>
    
  </div>

  <div class="form-actions">
      <div style="display: flex; float: left;">
          <%= link_to 'Back', appointments_path, class: "btn btn-warning btn-m"%>
      </div>
      <div style="display: flex; float: right;">
          <%= f.button :submit , class: "btn btn-success btn-m"%>
      </div>
  </div>

<% end %>

app/views/appointments/edit.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Edit Appointment
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', appointment: @appointment %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">
    </div>
</div>
<br><br>

<%= render 'partials/footer' %>

app/views/appointments/index.html.erb
<%= render 'partials/navbar' %>

<div class="jumbotron jumbotron-fluid">
<div class="container">

<h1 style="text-align: center;">Appointments</h1>
<br/>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Doctorprofile</th>
      <th scope="col">Patient</th>
      <th scope="col">Notes</th>
      <th scope="col">Date</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        
        <td><%= appointment.doctorprofile.Name %></td>
        <td><%= appointment.patient.Name %></td>
        <td><%= appointment.notes %></td>
        <td><%= appointment.date %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'D', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Appointment', new_appointment_path, class: "btn btn-success btn-m" %>

</div>
</div>

<%= render 'partials/footer' %>

app/views/appointments/new.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Make Appointment
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', appointment: @appointment %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">
    </div>
</div>
<br><br>

<%= render 'partials/footer' %>

app/views/appointments/show.html.erb
<%= render 'partials/navbar' %>

<br/><br/>
<div class="container ">
    <div class="jumbotron ">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                
            </div>
                <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                    <div class="container">
                        <h2 style="text-align:center;">
                            Appointment for : <%= @appointment.patient.name %>
                        </h2>
                    </div>
                    <hr class="colorgraph">

                    <ul class="container details">
                        <!--  Appointment Notes -->
                        <li><textarea readonly>Notes : <%= @appointment.notes %></textarea></li>
                        <!-- Patient Name-->
                        <li><p>Patient : <%= @appointment.patient.name %></p></li>

                    </ul>
                </div>
            </div>
        </div>
        <div style="display: flex; justify-content: center;">
            <%= link_to 'Back', appointments_path, class: "btn btn-dark btn-m" %> |
            <%= link_to 'Edit', edit_appointment_path(@appointment), class: "btn btn-warning btn-m" %>
        </div>
</div>

<%= render 'partials/footer' %>